In [1]:
import pandas as pd

In [2]:
pd.read_json('팀성적asJson/A조-팀순위.json')[
  ['rank','teamName','count','win','lose','draw','point','winPct','runs','pitRuns','batAvg']
]

,rank,teamName,count,win,lose,draw,point,winPct,runs,pitRuns,batAvg
0,1,Diamond Ace,9,7,2,0,21,0.778,113,44,0.446512
1,1,썬볼프라임,9,7,2,0,21,0.778,63,33,0.341463
2,3,토야,8,6,2,0,18,0.750,69,50,0.375000
3,4,25WARRIORS,6,5,1,0,15,0.833,59,43,0.342466
4,5,노에라,9,4,4,1,13,0.444,51,60,0.346939
5,6,디데이즈,7,4,3,0,12,0.571,64,40,0.364198
6,7,토리스,8,3,5,0,9,0.375,73,75,0.359788
7,8,라바,9,2,5,2,8,0.222,46,99,0.327044
8,9,Metros,7,2,4,1,7,0.286,61,68,0.411765
9,10,롯데면세점,10,1,8,1,4,0.100,33,93,0.337838
10,10,한국공항공사,8,1,6,1,4,0.125,49,76,0.287671

In [3]:
pd.read_json('팀성적asJson/A조-팀공격순위.json')[
  ['team_name','game_cnt','bat_avg','bat_tpa','bat_ab','bat_rbi','bat_runs','bat_hits','bat_b1','bat_b2','bat_b3','bat_hr']
]

,team_name,game_cnt,bat_avg,bat_tpa,bat_ab,bat_rbi,bat_runs,bat_hits,bat_b1,bat_b2,bat_b3,bat_hr
0,Diamond Ace,9,0.446512,278,215,95,113,96,54,25,4,13
1,Metros,7,0.411765,198,170,51,61,70,50,17,1,2
2,토야,8,0.375000,228,192,57,69,72,55,15,0,2
3,디데이즈,7,0.364198,207,162,50,64,59,43,12,1,3
4,토리스,8,0.359788,231,189,55,73,68,54,13,1,0
5,노에라,8,0.346939,234,196,49,51,68,50,13,0,5
6,25WARRIORS,6,0.342466,173,146,46,59,50,34,12,0,4
7,썬볼프라임,7,0.341463,205,164,50,63,56,43,11,2,0
8,롯데면세점,8,0.337838,174,148,24,33,50,32,16,1,1
9,라바,7,0.327044,182,159,36,46,52,35,15,1,1
10,한국공항공사,7,0.287671,196,146,38,49,42,28,10,1,3

In [4]:
pd.read_json('팀성적asJson/A조-팀공격순위.json')[
  ['bat_bb','bat_hbp','bat_tbase','bat_slg','bat_obp','bat_ops','bat_sb','bat_scb','bat_sf','bat_so','bat_gidp']
]

,bat_bb,bat_hbp,bat_tbase,bat_slg,bat_obp,bat_ops,bat_sb,bat_scb,bat_sf,bat_so,bat_gidp
0,48,8,168,0.781395,0.546763,1.328158,39,0,7,34,1
1,21,7,95,0.558824,0.494949,1.053773,20,0,0,41,1
2,28,8,93,0.484375,0.473684,0.958059,40,0,0,23,1
3,28,14,82,0.506173,0.487923,0.994096,30,0,3,33,1
4,31,8,83,0.439153,0.463203,0.902357,27,0,3,33,2
5,29,6,96,0.489796,0.440171,0.929967,20,0,3,36,0
6,20,6,74,0.506849,0.439306,0.946156,18,0,1,17,2
7,25,13,71,0.432927,0.458537,0.891463,30,0,3,27,1
8,19,3,71,0.479730,0.413793,0.893523,21,0,4,38,1
9,13,7,72,0.452830,0.395604,0.848435,27,0,3,33,2
10,39,8,63,0.431507,0.454082,0.885588,31,0,3,29,0

In [7]:
pd.read_json('팀성적asJson/A조-팀피칭순위.json')[
  ['team_name','game_cnt','pit_era','pit_win','pit_loss','pit_save','pit_hold','pit_inning','pit_bf','pit_ab']
]

,team_name,game_cnt,pit_era,pit_win,pit_loss,pit_save,pit_hold,pit_inning,pit_bf,pit_ab
0,디데이즈,7,2.457447,4,3,0,0,31.1,177,148
1,썬볼프라임,7,3.836538,5,2,0,0,34.2,178,154
2,Diamond Ace,9,3.926829,7,2,0,0,41.0,220,191
3,토야,8,5.612069,6,2,2,0,38.2,214,173
4,25WARRIORS,6,7.443038,5,1,0,0,26.1,155,131
5,노에라,8,7.809917,3,4,2,0,40.1,219,192
6,Metros,7,8.312500,2,4,0,0,32.0,208,159
7,한국공항공사,7,8.750000,1,4,0,0,32.0,218,177
8,라바,7,9.483871,1,4,0,0,31.0,242,202
9,토리스,8,10.805825,3,5,0,0,34.1,232,186
10,롯데면세점,8,30.606383,1,6,0,0,31.1,243,174

In [6]:
pd.read_json('팀성적asJson/A조-팀피칭순위.json')[
  ['pit_hits','pit_hr','pit_scf','pit_bb','pit_hbp','pit_so','pit_wp','pit_bk','pit_runs','pit_er']
]

,pit_hits,pit_hr,pit_scf,pit_bb,pit_hbp,pit_so,pit_wp,pit_bk,pit_runs,pit_er
0,34,0,2,21,6,30,5,2,40,11
1,44,2,2,13,9,30,1,0,33,19
2,62,5,3,18,8,41,3,0,44,23
3,55,3,3,33,5,35,7,0,50,31
4,55,5,1,17,6,20,1,1,43,28
5,73,3,3,23,1,35,6,0,60,45
6,54,3,2,38,9,48,10,3,68,38
7,67,2,4,24,13,30,9,4,76,40
8,94,4,1,30,9,20,5,3,99,42
9,73,5,5,34,7,28,0,2,75,53
10,72,2,4,50,15,27,12,6,93,137